set(
	REPLAY_SOURCE_FILES
	replay/gamedefs.h
	replay/gamedefs.cpp
	replay/replay_ragdoll.cpp
	replay/replay_ragdoll.h
	replay/replay_screenshot.cpp
	replay/replay_screenshot.h
	replay/replayperformanceplaybackhandler.h
	replay/replayperformanceplaybackhandler.cpp
	replay/replayrenderer.cpp
	replay/replayrenderer.h
	replay/replayvideo.cpp
	replay/replayvideo.h
	
	replay/genericclassbased_replay.cpp
	replay/genericclassbased_replay.h
	
	${SRC_DIR}/game/shared/replay_gamestats_shared.cpp
	${SRC_DIR}/game/shared/replay_gamestats_shared.h
	
	${SRC_DIR}/game/client/youtubeapi.h
	${SRC_DIR}/game/client/youtubeapi.cpp

	# Folder UI
	replay/vgui/replaybrowserbasepage.cpp
	replay/vgui/replaybrowserbasepage.h
	replay/vgui/replaybrowserbasepanel.cpp
	replay/vgui/replaybrowserbasepanel.h
	replay/vgui/replayconfirmquitdlg.cpp
	replay/vgui/replayconfirmquitdlg.h
	replay/vgui/replaybrowserdetailspanel.cpp
	replay/vgui/replaybrowserdetailspanel.h
	replay/vgui/replaybrowseritemmanager.cpp
	replay/vgui/replaybrowseritemmanager.h
	replay/vgui/replaybrowserlistitempanel.cpp
	replay/vgui/replaybrowserlistitempanel.h
	replay/vgui/replaybrowserlistpanel.cpp
	replay/vgui/replaybrowserlistpanel.h
	replay/vgui/replaybrowsermainpanel.cpp
	replay/vgui/replaybrowsermainpanel.h
	replay/vgui/replaybrowsermovieplayerpanel.cpp
	replay/vgui/replaybrowsermovieplayerpanel.h
	replay/vgui/replaybrowserpreviewpanel.cpp
	replay/vgui/replaybrowserpreviewpanel.h
	replay/vgui/replaybrowserrenderdialog.cpp
	replay/vgui/replaybrowserrenderdialog.h
	replay/vgui/replayinputpanel.cpp
	replay/vgui/replayinputpanel.h
	replay/vgui/replaymessagepanel.cpp
	replay/vgui/replaymessagepanel.h
	replay/vgui/replayperformanceeditor.cpp
	replay/vgui/replayperformanceeditor.h
	replay/vgui/replayperformancesavedlg.cpp
	replay/vgui/replayperformancesavedlg.h
	replay/vgui/replayrenderoverlay.cpp
	replay/vgui/replayrenderoverlay.h
	replay/vgui/replayreminderpanel.cpp
	replay/vgui/replayreminderpanel.h
	replay/replayyoutubeapi.cpp
	replay/replayyoutubeapi.h
	replay/replayyoutubeapi_key_sdk.cpp
	
	game_controls/slideshowpanel.cpp
	game_controls/slideshowpanel.h
	
	${SRC_DIR}/common/movieobjects/timeutils.cpp
	${SRC_DIR}/public/movieobjects/timeutils.h
)

set(
	CLIENT_BASE_SOURCE_FILES

	hl2/C_Func_Monitor.cpp
	geiger.cpp
	history_resource.cpp
	hud_weapon.cpp
	train.cpp
	${SRC_DIR}/game/shared/weapon_parse_default.cpp
	${SRC_DIR}/game/shared/achievement_saverestore.cpp
	${SRC_DIR}/game/shared/achievement_saverestore.h
	${SRC_DIR}/game/shared/achievementmgr.cpp
	${SRC_DIR}/game/shared/achievementmgr.h
	${SRC_DIR}/game/shared/achievements_and_stats_interface.h
	${SRC_DIR}/game/shared/achievements_hlx.cpp
	achievement_notification_panel.cpp
	achievement_notification_panel.h
	${SRC_DIR}/game/shared/activitylist.cpp
	alphamaterialproxy.cpp
	${SRC_DIR}/game/shared/ammodef.cpp
	animatedentitytextureproxy.cpp
	animatedoffsettextureproxy.cpp
	animatedtextureproxy.cpp
	AnimateSpecificTextureProxy.cpp
	${SRC_DIR}/game/shared/animation.cpp
	${SRC_DIR}/game/shared/base_playeranimstate.cpp
	${SRC_DIR}/game/shared/baseachievement.cpp
	${SRC_DIR}/game/shared/baseachievement.h
	baseanimatedtextureproxy.cpp
	baseclientrendertargets.cpp
	${SRC_DIR}/game/shared/basecombatcharacter_shared.cpp
	${SRC_DIR}/game/shared/basecombatweapon_shared.cpp
	${SRC_DIR}/game/shared/baseentity_shared.cpp
	${SRC_DIR}/game/shared/basegrenade_shared.cpp
	${SRC_DIR}/game/shared/baseparticleentity.cpp
	${SRC_DIR}/game/shared/baseplayer_shared.cpp
	${SRC_DIR}/game/shared/baseprojectile.cpp
	${SRC_DIR}/game/shared/baseprojectile.h
	${SRC_DIR}/game/shared/baseviewmodel_shared.cpp
	beamdraw.cpp
	${SRC_DIR}/game/shared/beam_shared.cpp
	${SRC_DIR}/public/bone_accessor.cpp
	bone_merge_cache.cpp
	c_ai_basehumanoid.cpp
	c_ai_basenpc.cpp
	c_baseanimating.cpp
	c_baseanimatingoverlay.cpp
	c_basecombatcharacter.cpp
	c_basecombatweapon.cpp
	c_basedoor.cpp
	c_baseentity.cpp
	c_baseflex.cpp
	c_baseplayer.cpp
	c_baseviewmodel.cpp
	c_breakableprop.cpp
	c_colorcorrection.cpp
	c_colorcorrectionvolume.cpp
	c_dynamiclight.cpp
	c_entitydissolve.cpp
	c_entityparticletrail.cpp
	c_env_fog_controller.cpp
	c_env_particlescript.cpp
	c_env_projectedtexture.cpp
	c_env_screenoverlay.cpp
	c_env_tonemap_controller.cpp
	c_fire_smoke.cpp
	c_fish.cpp
	c_func_areaportalwindow.cpp
	c_func_breakablesurf.cpp
	c_func_conveyor.cpp
	c_func_dust.cpp
	c_func_lod.cpp
	c_func_occluder.cpp
	c_func_reflective_glass.cpp
	c_func_rotating.cpp
	c_func_smokevolume.cpp
	c_func_tracktrain.cpp
	c_gib.cpp
	c_hairball.cpp
	c_info_overlay_accessor.cpp
	c_lightglow.cpp
	C_MaterialModifyControl.cpp
	c_particle_system.cpp
	c_physbox.cpp
	c_physicsprop.cpp
	c_physmagnet.cpp
	c_pixel_visibility.cpp
	c_plasma.cpp
	c_playerresource.cpp
	c_point_camera.cpp
	c_point_commentary_node.cpp
	c_props.cpp
	c_props.h
	c_ragdoll_manager.cpp
	c_rope.cpp
	c_rumble.cpp
	c_sceneentity.cpp
	c_shadowcontrol.cpp
	c_slideshow_display.cpp
	c_slideshow_display.h
	c_soundscape.cpp
	c_spotlight_end.cpp
	c_sprite.cpp
	c_sprite_perfmonitor.cpp
	c_sun.cpp
	c_team.cpp
	c_tesla.cpp
	c_test_proxytoggle.cpp
	c_user_message_register.cpp
	c_vehicle_choreo_generic.cpp
	c_vehicle_jeep.cpp
	c_vguiscreen.cpp
	hl2/c_waterbullet.cpp
	hl2/hud_autoaim.cpp
	C_WaterLODControl.cpp
	c_world.cpp
	${SRC_DIR}/game/shared/cam_thirdperson.cpp
	${SRC_DIR}/game/shared/cam_thirdperson.h
	camomaterialproxy.cpp
	cdll_client_int.cpp
	cdll_bounded_cvars.cpp
	cdll_bounded_cvars.h
	cdll_util.cpp
	cl_mat_stub.cpp
	classmap.cpp
	client_factorylist.cpp
	client_thinklist.cpp
	client_virtualreality.cpp
	client_virtualreality.h
	clienteffectprecachesystem.cpp
	cliententitylist.cpp
	clientleafsystem.cpp
	clientmode_shared.cpp
	clientshadowmgr.cpp
	clientsideeffects.cpp
	clientsideeffects_test.cpp
	clientsteamcontext.cpp
	clientsteamcontext.h
	colorcorrectionmgr.cpp
	commentary_modelviewer.cpp
	commentary_modelviewer.h
	${SRC_DIR}/game/shared/collisionproperty.cpp
	${SRC_DIR}/game/shared/death_pose.cpp
	${SRC_DIR}/game/shared/debugoverlay_shared.cpp
	${SRC_DIR}/game/shared/decals.cpp
	detailobjectsystem.cpp
	dummyproxy.cpp
	${SRC_DIR}/game/shared/effect_dispatch_data.cpp
	EffectsClient.cpp
	${SRC_DIR}/game/shared/ehandle.cpp
	${SRC_DIR}/game/shared/entitylist_base.cpp
	entityoriginmaterialproxy.cpp
	${SRC_DIR}/game/shared/EntityParticleTrail_Shared.cpp
	${SRC_DIR}/game/shared/env_detail_controller.cpp
	${SRC_DIR}/game/shared/env_wind_shared.cpp
	${SRC_DIR}/game/shared/eventlist.cpp
	flashlighteffect.cpp
	${SRC_DIR}/game/shared/func_ladder.cpp
	functionproxy.cpp
	fx_blood.cpp
	fx_cube.cpp
	fx_explosion.cpp
	fx_fleck.cpp
	fx_impact.cpp
	fx_interpvalue.cpp
	fx_quad.cpp
	fx_shelleject.cpp
	fx_staticline.cpp
	fx_tracer.cpp
	fx_trail.cpp
	fx_water.cpp
	${SRC_DIR}/game/shared/gamemovement.cpp
	${SRC_DIR}/game/shared/gamerules.cpp
	${SRC_DIR}/game/shared/gamerules_register.cpp
	${SRC_DIR}/game/shared/GameStats.cpp
	${SRC_DIR}/game/shared/gamestringpool.cpp
	gametrace_client.cpp
	${SRC_DIR}/game/shared/gamevars_shared.cpp
	glow_outline_effect.cpp
	glow_overlay.cpp
	${SRC_DIR}/game/shared/hintmessage.cpp
	${SRC_DIR}/game/shared/hintsystem.cpp
	hltvcamera.cpp
	hud.cpp
	hud_animationinfo.cpp
	hud_basechat.cpp
	hud_basetimer.cpp
	hud_bitmapnumericdisplay.cpp
	hud_closecaption.cpp
	hud_crosshair.cpp
	hud_element_helper.cpp
	hl2/hud_filmdemo.cpp
	hl2/hud_hdrdemo.cpp
	hud_hintdisplay.cpp
	hud_msg.cpp
	hud_numericdisplay.cpp
	hud_pdump.cpp
	hud_redraw.cpp
	hud_vehicle.cpp
	${SRC_DIR}/game/shared/igamesystem.cpp
	in_camera.cpp
	in_joystick.cpp
	in_main.cpp
	initializer.cpp
	interpolatedvar.cpp
	IsNPCProxy.cpp
	lampbeamproxy.cpp
	lamphaloproxy.cpp
	${SRC_DIR}/game/shared/mapentities_shared.cpp
	mathproxy.cpp
	matrixproxy.cpp
	menu.cpp
	message.cpp
	movehelper_client.cpp
	${SRC_DIR}/game/shared/movevars_shared.cpp
	${SRC_DIR}/game/shared/multiplay_gamerules.cpp
	${SRC_DIR}/game/shared/obstacle_pushaway.cpp
	panelmetaclassmgr.cpp
	particle_collision.cpp
	particle_litsmokeemitter.cpp
	${SRC_DIR}/game/shared/particle_parse.cpp
	${SRC_DIR}/game/shared/particle_parse.h
	${SRC_DIR}/game/shared/particle_property.cpp
	${SRC_DIR}/game/shared/particle_property.h
	particle_proxies.cpp
	particle_simple3d.cpp
	particlemgr.cpp
	particles_attractor.cpp
	particles_ez.cpp
	particles_localspace.cpp
	particles_new.cpp
	particles_simple.cpp
	${SRC_DIR}/game/shared/particlesystemquery.cpp
	perfvisualbenchmark.cpp
	physics.cpp
	physics_main_client.cpp
	${SRC_DIR}/game/shared/physics_main_shared.cpp
	${SRC_DIR}/game/shared/physics_saverestore.cpp
	${SRC_DIR}/game/shared/physics_shared.cpp
	physpropclientside.cpp
	playerandobjectenumerator.cpp
	playerspawncache.cpp
	${SRC_DIR}/game/shared/point_bonusmaps_accessor.cpp
	${SRC_DIR}/game/shared/point_bonusmaps_accessor.h
	${SRC_DIR}/game/shared/point_posecontroller.cpp
	${SRC_DIR}/game/shared/precache_register.cpp
	${SRC_DIR}/game/shared/predictableid.cpp
	prediction.cpp
	${SRC_DIR}/game/shared/predictioncopy.cpp
	${SRC_DIR}/game/shared/props_shared.cpp
	proxyentity.cpp
	ProxyHealth.cpp
	proxyplayer.cpp
	proxypupil.cpp
	ragdoll.cpp
	${SRC_DIR}/game/shared/ragdoll_shared.cpp
	recvproxy.cpp
	basepresence.cpp
	${SRC_DIR}/game/shared/rope_helpers.cpp
	${SRC_DIR}/game/shared/saverestore.cpp
	${SRC_DIR}/game/shared/sceneentity_shared.cpp
	ScreenSpaceEffects.cpp
	${SRC_DIR}/game/shared/sequence_Transitioner.cpp
	simple_keys.cpp
	${SRC_DIR}/game/shared/simtimer.cpp
	${SRC_DIR}/game/shared/singleplay_gamerules.cpp
	${SRC_DIR}/game/shared/SoundEmitterSystem.cpp
	${SRC_DIR}/game/shared/soundenvelope.cpp
	${SRC_DIR}/public/SoundParametersInternal.cpp
	splinepatch.cpp
	${SRC_DIR}/game/shared/Sprite.cpp
	spritemodel.cpp
	${SRC_DIR}/game/shared/SpriteTrail.cpp
	${SRC_DIR}/game/shared/studio_shared.cpp
	studio_stats.cpp
	studio_stats.h
	${SRC_DIR}/game/shared/takedamageinfo.cpp
	${SRC_DIR}/game/shared/teamplay_gamerules.cpp
	${SRC_DIR}/game/shared/teamplayroundbased_gamerules.cpp
	${SRC_DIR}/game/shared/test_ehandle.cpp
	text_message.cpp
	texturescrollmaterialproxy.cpp
	timematerialproxy.cpp
	toggletextureproxy.cpp
	${SRC_DIR}/game/shared/usercmd.cpp
	${SRC_DIR}/game/shared/usermessages.cpp
	${SRC_DIR}/game/shared/util_shared.cpp
	${SRC_DIR}/game/shared/vehicle_viewblend_shared.cpp
	vgui_avatarimage.cpp
	vgui_avatarimage.h
	vgui_basepanel.cpp
	vgui_bitmapbutton.cpp
	vgui_bitmapimage.cpp
	vgui_bitmappanel.cpp
	vgui_schemevisualizer.cpp
	vgui_centerstringpanel.cpp
	vgui_consolepanel.cpp
	vgui_debugoverlaypanel.cpp
	vgui_fpspanel.cpp
	vgui_game_viewport.cpp
	vgui_grid.cpp
	vgui_int.cpp
	vgui_loadingdiscpanel.cpp
	vgui_messagechars.cpp
	vgui_netgraphpanel.cpp
	vgui_slideshow_display_screen.cpp
	view.cpp
	view_beams.cpp
	view_effects.cpp
	view_scene.cpp
	viewangleanim.cpp
	ViewConeImage.cpp
	viewdebug.cpp
	viewdebug.h
	viewpostprocess.cpp
	viewpostprocess.h
	viewrender.cpp
	${SRC_DIR}/game/shared/voice_banmgr.cpp
	${SRC_DIR}/game/shared/voice_status.cpp
	warp_overlay.cpp
	WaterLODMaterialProxy.cpp
	${SRC_DIR}/game/shared/weapon_parse.cpp
	weapon_selection.cpp
	weapons_resource.cpp
	WorldDimsProxy.cpp
	vgui_video.cpp
	vgui_video_player.cpp
	${SRC_DIR}/game/shared/mp_shareddefs.cpp
	${SRC_DIR}/game/client/c_vote_controller.h
	${SRC_DIR}/game/client/c_vote_controller.cpp
	${SRC_DIR}/public/bone_setup.cpp
	${SRC_DIR}/public/posedebugger.cpp
	${SRC_DIR}/public/client_class.cpp
	${SRC_DIR}/common/compiledcaptionswap.cpp
	${SRC_DIR}/public/collisionutils.cpp
	${SRC_DIR}/public/crtmemdebug.cpp
	${SRC_DIR}/public/dt_recv.cpp
	${SRC_DIR}/public/dt_utlvector_common.cpp
	${SRC_DIR}/public/dt_utlvector_recv.cpp
	${SRC_DIR}/public/filesystem_helpers.cpp
	${SRC_DIR}/public/interpolatortypes.cpp
	${SRC_DIR}/game/shared/interval.cpp
	${SRC_DIR}/common/language.cpp
	${SRC_DIR}/public/networkvar.cpp
	${SRC_DIR}/common/randoverride.cpp
	${SRC_DIR}/public/rope_physics.cpp
	${SRC_DIR}/public/scratchpad3d.cpp
	${SRC_DIR}/public/ScratchPadUtils.cpp
	${SRC_DIR}/public/sentence.cpp
	${SRC_DIR}/game/shared/sheetsimulator.cpp
	${SRC_DIR}/public/simple_physics.cpp
	${SRC_DIR}/public/stringregistry.cpp
	${SRC_DIR}/public/studio.cpp
	${SRC_DIR}/public/vallocator.cpp
	${SRC_DIR}/public/vgui_controls/vgui_controls.cpp
	${SRC_DIR}/public/jigglebones.cpp
	hud_lcd.cpp
	in_mouse.cpp
	mumble.cpp
	${SRC_DIR}/public/renamed_recvtable_compat.cpp
	rendertexture.cpp
)

source_group("Source Files" FILES ${CLIENT_BASE_SOURCE_FILES})

set(CLIENT_MP3_SOURCES
	mp3player.cpp
	mp3player.h
)
source_group("MP3" FILES ${CLIENT_MP3_SOURCES})

set(CLIENT_REPLAY_SOURCES
	replay/replaycamera.cpp
	replay/replaycamera.h
	replay/cdll_replay.cpp
	replay/cdll_replay.h

	$<${BUILD_REPLAY}:${REPLAY_SOURCE_FILES}>
)

source_group("Replay" FILES ${CLIENT_REPLAY_SOURCES})

set(CLIENT_TOOLFRAMEWORK_SOURCES
	${SRC_DIR}/public/tools/bonelist.cpp
	${SRC_DIR}/public/tools/bonelist.h
	entity_client_tools.cpp
	toolframework_client.cpp
	toolframework_client.h
)

source_group("Tool Framework" FILES ${CLIENT_TOOLFRAMEWORK_SOURCES})

set(CLIENT_SIXENSE_SOURCES
	sixense/in_sixense.cpp
	sixense/in_sixense.h
	sixense/in_sixense_gesture_bindings.cpp
	sixense/in_sixense_gesture_bindings.h
	${SRC_DIR}/game/shared/sixense/sixense_convars.cpp
	${SRC_DIR}/game/shared/sixense/sixense_convars_extern.h
)

source_group("Sixense" FILES ${CLIENT_SIXENSE_SOURCES})

set(TEMPENTS_SOURCES
	# Temporary Entities
	c_basetempentity.cpp
	c_effects.cpp
	c_impact_effects.cpp
	c_movie_explosion.cpp
	c_particle_fire.cpp
	c_particle_smokegrenade.cpp
	c_prop_vehicle.cpp
	c_recipientfilter.cpp
	c_smoke_trail.cpp
	c_smokestack.cpp
	c_steamjet.cpp
	c_stickybolt.cpp
	c_te.cpp
	c_te_armorricochet.cpp
	c_te_basebeam.cpp
	c_te_beamentpoint.cpp
	c_te_beaments.cpp
	c_te_beamfollow.cpp
	c_te_beamlaser.cpp
	c_te_beampoints.cpp
	c_te_beamring.cpp
	c_te_beamringpoint.cpp
	c_te_beamspline.cpp
	c_te_bloodsprite.cpp
	c_te_bloodstream.cpp
	c_te_breakmodel.cpp
	c_te_bspdecal.cpp
	c_te_bubbles.cpp
	c_te_bubbletrail.cpp
	c_te_clientprojectile.cpp
	c_te_decal.cpp
	c_te_dynamiclight.cpp
	c_te_effect_dispatch.cpp
	c_te_energysplash.cpp
	c_te_explosion.cpp
	c_te_fizz.cpp
	c_te_footprint.cpp
	c_te_glassshatter.cpp
	c_te_glowsprite.cpp
	c_te_impact.cpp
	c_te_killplayerattachments.cpp
	c_te_largefunnel.cpp
	c_te_legacytempents.cpp
	c_te_muzzleflash.cpp
	c_te_particlesystem.cpp
	c_te_physicsprop.cpp
	c_te_playerdecal.cpp
	c_te_projecteddecal.cpp
	c_te_showline.cpp
	c_te_smoke.cpp
	c_te_sparks.cpp
	c_te_sprite.cpp
	c_te_spritespray.cpp
	c_te_worlddecal.cpp
	c_testtraceline.cpp
	c_tracer.cpp
	fx.cpp
	fx_discreetline.cpp
	fx_envelope.cpp
	fx_line.cpp
	fx_sparks.cpp
	particlesphererenderer.cpp
	smoke_fog_overlay.cpp
)

source_group("Source Files/Temporary Entities" FILES ${TEMPENTS_SOURCES})

set(CLIENT_BASE_HEADER_FILES
	# Header Files
	animationlayer.h
	baseanimatedtextureproxy.h
	baseclientrendertargets.h
	beamdraw.h
	bone_merge_cache.h
	c_ai_basenpc.h
	c_baseanimating.h
	c_baseanimatingoverlay.h
	c_basecombatcharacter.h
	c_basecombatweapon.h
	c_basedoor.h
	c_baseentity.h
	c_baseflex.h
	c_baseplayer.h
	c_basetempentity.h
	c_baseviewmodel.h
	c_breakableprop.h
	c_effects.h
	c_entitydissolve.h
	c_env_fog_controller.h
	c_fire_smoke.h
	c_func_dust.h
	c_func_reflective_glass.h
	c_gib.h
	c_impact_effects.h
	c_physbox.h
	c_physicsprop.h
	c_pixel_visibility.h
	c_playerlocaldata.h
	c_playerresource.h
	c_point_camera.h
	c_prop_vehicle.h
	c_recipientfilter.h
	c_rope.h
	c_rumble.h
	c_sceneentity.h
	c_smoke_trail.h
	c_soundscape.h
	c_sprite.h
	c_sun.h
	c_te_basebeam.h
	c_te_effect_dispatch.h
	c_te_legacytempents.h
	c_te_particlesystem.h
	c_team.h
	c_tesla.h
	c_tracer.h
	c_vehicle_jeep.h
	c_user_message_register.h
	c_vguiscreen.h
	c_weapon__stubs.h
	c_world.h
	cbase.h
	cdll_client_int.h
	cdll_util.h
	cl_animevent.h
	cl_mat_stub.h
	client_factorylist.h
	client_thinklist.h
	clienteffectprecachesystem.h
	cliententitylist.h
	clientleafsystem.h
	clientmode.h
	clientmode_shared.h
	clientsideeffects.h
	colorcorrectionmgr.h
	detailobjectsystem.h
	enginesprite.h
	flashlighteffect.h
	fontabc.h
	functionproxy.h
	fx.h
	fx_blood.h
	fx_discreetline.h
	fx_envelope.h
	fx_explosion.h
	fx_fleck.h
	fx_impact.h
	fx_interpvalue.h
	fx_line.h
	fx_quad.h
	fx_sparks.h
	fx_staticline.h
	fx_trail.h
	fx_water.h
	${SRC_DIR}/game/shared/GameEventListener.h
	glow_outline_effect.h
	glow_overlay.h
	${SRC_DIR}/game/shared/hintmessage.h
	${SRC_DIR}/game/shared/hintsystem.h
	history_resource.h
	hltvcamera.h
	hud.h
	hud_basechat.h
	hud_basetimer.h
	hud_bitmapnumericdisplay.h
	hud_chat.h
	hud_closecaption.h
	hud_crosshair.h
	hud_element_helper.h
	hud_lcd.h
	hud_macros.h
	hud_numericdisplay.h
	hud_pdump.h
	basepresence.h
	hud_vehicle.h
	hudelement.h
	hudtexturehandle.h
	iclassmap.h
	icliententityinternal.h
	iclientmode.h
	iclientshadowmgr.h
	iclientvehicle.h
	iconsole.h
	idebugoverlaypanel.h
	ifpspanel.h
	${SRC_DIR}/game/shared/econ/ihasowner.h
	ihudlcd.h
	ipresence.h
	iinput.h
	iloadingdisc.h
	imessagechars.h
	in_main.h
	inetgraphpanel.h
	initializer.h
	input.h
	interpolatedvar.h
	iprofiling.h
	itextmessage.h
	ivieweffects.h
	iviewrender.h
	iviewrender_beams.h
	ivmodemanager.h
	kbutton.h
	${SRC_DIR}/common/language.h
	lerp_functions.h
	menu.h
	movehelper_client.h
	mumble.h
	networkstringtable_clientdll.h
	panelmetaclassmgr.h
	particle_collision.h
	particle_iterators.h
	particle_litsmokeemitter.h
	particle_prototype.h
	particle_simple3d.h
	particle_util.h
	particledraw.h
	particlemgr.h
	particles_attractor.h
	particles_ez.h
	particles_localspace.h
	particles_new.h
	particles_simple.h
	particlesphererenderer.h
	perfvisualbenchmark.h
	physics.h
	physpropclientside.h
	playerandobjectenumerator.h
	playerenumerator.h
	playerspawncache.h
	prediction.h
	prediction_private.h
	proxyentity.h
	ragdoll.h
	ragdollexplosionenumerator.h
	recvproxy.h
	rendertexture.h
	ScreenSpaceEffects.h
	simple_keys.h
	smoke_fog_overlay.h
	splinepatch.h
	${SRC_DIR}/public/steam/steam_api.h
	TeamBitmapImage.h
	tempent.h
	text_message.h
	timedevent.h
	toggletextureproxy.h
	vgui_basepanel.h
	vgui_bitmapbutton.h
	vgui_bitmapimage.h
	vgui_bitmappanel.h
	vgui_schemevisualizer.h
	vgui_entityimagepanel.h
	vgui_entitypanel.h
	vgui_grid.h
	vgui_helpers.h
	vgui_imagehealthpanel.h
	vgui_int.h
	vguicenterprint.h
	view.h
	view_scene.h
	viewangleanim.h
	ViewConeImage.h
	viewrender.h
	weapon_selection.h
	weapons_resource.h
	vgui_video.h
	vgui_video_player.h
)

source_group("Header Files" FILES ${CLIENT_BASE_HEADER_FILES})

set(GAME_SHARED_HEADER_FILES
	${SRC_DIR}/game/shared/activitylist.h
	${SRC_DIR}/game/shared/ai_activity.h
	${SRC_DIR}/game/shared/ai_debug_shared.h
	${SRC_DIR}/game/shared/ammodef.h
	${SRC_DIR}/game/shared/animation.h
	${SRC_DIR}/game/shared/apparent_velocity_helper.h
	${SRC_DIR}/game/shared/base_playeranimstate.h
	${SRC_DIR}/game/shared/baseentity_shared.h
	${SRC_DIR}/game/shared/basegrenade_shared.h
	${SRC_DIR}/game/shared/hl2/basehlcombatweapon_shared.h
	${SRC_DIR}/game/shared/baseparticleentity.h
	${SRC_DIR}/game/shared/baseplayer_shared.h
	${SRC_DIR}/game/shared/baseviewmodel_shared.h
	${SRC_DIR}/game/shared/beam_flags.h
	${SRC_DIR}/game/shared/beam_shared.h
	${SRC_DIR}/game/shared/choreoactor.h
	${SRC_DIR}/game/shared/choreochannel.h
	${SRC_DIR}/game/shared/choreoevent.h
	${SRC_DIR}/game/shared/choreoscene.h
	${SRC_DIR}/game/shared/collisionproperty.h
	${SRC_DIR}/game/shared/death_pose.h
	${SRC_DIR}/game/shared/decals.h
	${SRC_DIR}/game/shared/effect_color_tables.h
	${SRC_DIR}/game/shared/effect_dispatch_data.h
	${SRC_DIR}/game/shared/ehandle.h
	${SRC_DIR}/game/shared/entitydatainstantiator.h
	${SRC_DIR}/game/shared/entitylist_base.h
	${SRC_DIR}/game/shared/entityparticletrail_shared.h
	${SRC_DIR}/game/shared/env_detail_controller.h
	${SRC_DIR}/game/shared/env_wind_shared.h
	${SRC_DIR}/game/shared/eventlist.h
	${SRC_DIR}/game/shared/func_dust_shared.h
	${SRC_DIR}/game/shared/func_ladder.h
	${SRC_DIR}/game/shared/gameeventdefs.h
	${SRC_DIR}/game/shared/gamemovement.h
	${SRC_DIR}/game/shared/gamerules.h
	${SRC_DIR}/game/shared/gamerules_register.h
	${SRC_DIR}/game/shared/gamestats.h
	${SRC_DIR}/game/shared/gamestringpool.h
	${SRC_DIR}/game/shared/gamevars_shared.h
	${SRC_DIR}/game/shared/groundlink.h
	${SRC_DIR}/game/shared/hl2/hl2_player_shared.h
	${SRC_DIR}/game/shared/hl2/hl_movedata.h
	${SRC_DIR}/game/shared/ichoreoeventcallback.h
	${SRC_DIR}/game/shared/IEffects.h
	${SRC_DIR}/game/shared/igamemovement.h
	${SRC_DIR}/game/shared/igamesystem.h
	${SRC_DIR}/game/shared/imovehelper.h
	${SRC_DIR}/game/shared/in_buttons.h
	${SRC_DIR}/game/shared/interval.h
	${SRC_DIR}/game/shared/iplayeranimstate.h
	${SRC_DIR}/game/shared/ipredictionsystem.h
	${SRC_DIR}/game/shared/itempents.h
	${SRC_DIR}/game/shared/IVehicle.h
	${SRC_DIR}/game/shared/mapdata_shared.h
	${SRC_DIR}/game/shared/mapentities_shared.h
	${SRC_DIR}/game/shared/movevars_shared.h
	${SRC_DIR}/game/shared/multiplay_gamerules.h
	${SRC_DIR}/game/shared/npcevent.h
	${SRC_DIR}/game/shared/obstacle_pushaway.h
	${SRC_DIR}/game/shared/physics_saverestore.h
	${SRC_DIR}/game/shared/physics_shared.h
	${SRC_DIR}/game/shared/playernet_vars.h
	${SRC_DIR}/game/shared/point_posecontroller.h
	${SRC_DIR}/game/shared/positionwatcher.h
	${SRC_DIR}/game/shared/precache_register.h
	${SRC_DIR}/game/shared/precipitation_shared.h
	${SRC_DIR}/game/shared/predictable_entity.h
	${SRC_DIR}/game/shared/predictableid.h
	${SRC_DIR}/game/shared/predictioncopy.h
	${SRC_DIR}/game/shared/ragdoll_shared.h
	${SRC_DIR}/game/shared/rope_helpers.h
	${SRC_DIR}/game/shared/saverestore.h
	${SRC_DIR}/game/shared/saverestore_bitstring.h
	${SRC_DIR}/game/shared/saverestore_utlclass.h
	${SRC_DIR}/game/shared/saverestore_utlsymbol.h
	${SRC_DIR}/game/shared/saverestore_utlvector.h
	${SRC_DIR}/game/shared/sceneentity_shared.h
	${SRC_DIR}/game/shared/scriptevent.h
	${SRC_DIR}/game/shared/sequence_Transitioner.h
	${SRC_DIR}/game/shared/shared_classnames.h
	${SRC_DIR}/game/shared/shareddefs.h
	${SRC_DIR}/game/shared/sharedInterface.h
	${SRC_DIR}/game/shared/sheetsimulator.h
	${SRC_DIR}/game/shared/shot_manipulator.h
	${SRC_DIR}/game/shared/simtimer.h
	${SRC_DIR}/game/shared/singleplay_gamerules.h
	${SRC_DIR}/game/shared/smoke_fog_overlay_shared.h
	${SRC_DIR}/game/shared/solidsetdefaults.h
	${SRC_DIR}/game/shared/soundenvelope.h
	${SRC_DIR}/game/shared/Sprite.h
	${SRC_DIR}/game/shared/SpriteTrail.h
	${SRC_DIR}/game/shared/sun_shared.h
	${SRC_DIR}/game/shared/takedamageinfo.h
	${SRC_DIR}/game/shared/teamplay_gamerules.h
	${SRC_DIR}/game/shared/teamplayroundbased_gamerules.h
	${SRC_DIR}/game/shared/tempentity.h
	${SRC_DIR}/game/shared/touchlink.h
	${SRC_DIR}/game/shared/usercmd.h
	${SRC_DIR}/game/shared/usermessages.h
	${SRC_DIR}/game/shared/util_shared.h
	${SRC_DIR}/game/shared/vehicle_choreo_generic_shared.h
	${SRC_DIR}/game/shared/vehicle_viewblend_shared.h
	${SRC_DIR}/game/shared/vgui_defaultinputsignal.h
	${SRC_DIR}/game/shared/viewport_panel_names.h
	${SRC_DIR}/game/shared/voice_banmgr.h
	${SRC_DIR}/game/shared/voice_common.h
	${SRC_DIR}/game/shared/voice_gamemgr.h
	${SRC_DIR}/game/shared/voice_status.h
	${SRC_DIR}/game/shared/vphysics_sound.h
	${SRC_DIR}/game/shared/weapon_parse.h
	${SRC_DIR}/game/shared/weapon_proficiency.h
	${SRC_DIR}/game/shared/weapon_ifmsteadycam.h
	${SRC_DIR}/game/shared/mp_shareddefs.h
)

source_group("Game Shared Header Files" FILES ${GAME_SHARED_HEADER_FILES})

set(PUBLIC_HEADER_FILES
	${SRC_DIR}/public/mathlib/amd3dx.h
	${SRC_DIR}/public/vgui_controls/AnimationController.h
	${SRC_DIR}/public/basehandle.h
	${SRC_DIR}/public/tier0/basetypes.h
	${SRC_DIR}/public/tier1/bitbuf.h
	${SRC_DIR}/public/bitvec.h
	${SRC_DIR}/public/bone_accessor.h
	${SRC_DIR}/public/bone_setup.h
	${SRC_DIR}/public/bspfile.h
	${SRC_DIR}/public/bspflags.h
	${SRC_DIR}/public/bsptreedata.h
	${SRC_DIR}/public/mathlib/bumpvects.h
	${SRC_DIR}/public/vgui_controls/Button.h
	${SRC_DIR}/public/cdll_int.h
	${SRC_DIR}/public/tier1/characterset.h
	${SRC_DIR}/public/tier1/checksum_md5.h
	${SRC_DIR}/public/client_class.h
	${SRC_DIR}/public/client_render_handle.h
	${SRC_DIR}/public/client_textmessage.h
	${SRC_DIR}/public/clientstats.h
	${SRC_DIR}/public/cmodel.h
	${SRC_DIR}/public/vphysics/collision_set.h
	${SRC_DIR}/public/collisionutils.h
	${SRC_DIR}/public/Color.h
	${SRC_DIR}/public/vgui_controls/ComboBox.h
	${SRC_DIR}/public/tier0/commonmacros.h
	${SRC_DIR}/public/mathlib/compressed_light_cube.h
	${SRC_DIR}/public/mathlib/compressed_vector.h
	${SRC_DIR}/public/con_nprint.h
	${SRC_DIR}/public/const.h
	${SRC_DIR}/public/vphysics/constraints.h
	${SRC_DIR}/public/vgui_controls/Controls.h
	${SRC_DIR}/public/tier1/convar.h
	${SRC_DIR}/public/coordsize.h
	${SRC_DIR}/public/crtmemdebug.h
	${SRC_DIR}/public/vgui/Cursor.h
	${SRC_DIR}/public/vgui/Dar.h
	${SRC_DIR}/public/datamap.h
	${SRC_DIR}/public/tier0/dbg.h
	${SRC_DIR}/public/dlight.h
	${SRC_DIR}/public/dt_common.h
	${SRC_DIR}/public/dt_recv.h
	${SRC_DIR}/public/dt_send.h
	${SRC_DIR}/public/dt_utlvector_common.h
	${SRC_DIR}/public/dt_utlvector_recv.h
	${SRC_DIR}/public/edict.h
	${SRC_DIR}/public/vgui_controls/EditablePanel.h
	${SRC_DIR}/public/tier0/fasttimer.h
	${SRC_DIR}/public/filesystem.h
	${SRC_DIR}/public/filesystem_helpers.h
	${SRC_DIR}/public/tier1/fmtstr.h
	${SRC_DIR}/public/vgui_controls/FocusNavGroup.h
	${SRC_DIR}/public/vphysics/friction.h
	${SRC_DIR}/public/gamebspfile.h
	${SRC_DIR}/public/gametrace.h
	${SRC_DIR}/public/globalvars_base.h
	${SRC_DIR}/public/vgui_controls/HTML.h
	${SRC_DIR}/public/iachievementmgr.h
	${SRC_DIR}/public/appframework/IAppSystem.h
	${SRC_DIR}/public/icliententity.h
	${SRC_DIR}/public/icliententitylist.h
	${SRC_DIR}/public/engine/IClientLeafSystem.h
	${SRC_DIR}/public/iclientnetworkable.h
	${SRC_DIR}/public/vgui/IClientPanel.h
	${SRC_DIR}/public/iclientrenderable.h
	${SRC_DIR}/public/game/client/iclientrendertargets.h
	${SRC_DIR}/public/iclientthinkable.h
	${SRC_DIR}/public/iclientunknown.h
	${SRC_DIR}/public/engine/ICollideable.h
	${SRC_DIR}/public/tier0/icommandline.h
	${SRC_DIR}/public/icvar.h
	${SRC_DIR}/public/iefx.h
	${SRC_DIR}/public/engine/IEngineSound.h
	${SRC_DIR}/public/engine/IEngineTrace.h
	${SRC_DIR}/public/ienginevgui.h
	${SRC_DIR}/public/igameevents.h
	${SRC_DIR}/public/igameresources.h
	${SRC_DIR}/public/IGameUIFuncs.h
	${SRC_DIR}/public/ihandleentity.h
	${SRC_DIR}/public/vgui/IHTML.h
	${SRC_DIR}/public/vgui/IImage.h
	${SRC_DIR}/public/vgui/IInput.h
	${SRC_DIR}/public/vgui/IInputInternal.h
	${SRC_DIR}/public/vstdlib/IKeyValuesSystem.h
	${SRC_DIR}/public/vgui/ILocalize.h
	${SRC_DIR}/public/vgui_controls/Image.h
	${SRC_DIR}/public/vgui_controls/ImageList.h
	${SRC_DIR}/public/vgui_controls/ImagePanel.h
	${SRC_DIR}/public/imapoverview.h
	${SRC_DIR}/public/materialsystem/imaterial.h
	${SRC_DIR}/public/materialsystem/imaterialproxy.h
	${SRC_DIR}/public/materialsystem/imaterialsystem.h
	${SRC_DIR}/public/materialsystem/imaterialsystemhardwareconfig.h
	${SRC_DIR}/public/materialsystem/imaterialsystemstub.h
	${SRC_DIR}/public/materialsystem/imaterialvar.h
	${SRC_DIR}/public/VGuiMatSurface/IMatSystemSurface.h
	${SRC_DIR}/public/materialsystem/imesh.h
	${SRC_DIR}/public/inetchannelinfo.h
	${SRC_DIR}/public/tier1/interface.h
	${SRC_DIR}/public/interpolatortypes.h
	${SRC_DIR}/public/vgui/IPanel.h
	${SRC_DIR}/public/iprediction.h
	${SRC_DIR}/public/irecipientfilter.h
	${SRC_DIR}/public/isaverestore.h
	${SRC_DIR}/public/vgui/IScheme.h
	${SRC_DIR}/public/iscratchpad3d.h
	${SRC_DIR}/public/iserverentity.h
	${SRC_DIR}/public/iservernetworkable.h
	${SRC_DIR}/public/iserverunknown.h
	${SRC_DIR}/public/engine/ishadowmgr.h
	${SRC_DIR}/public/SoundEmitterSystem/isoundemittersystembase.h
	${SRC_DIR}/public/ispatialpartition.h
	${SRC_DIR}/public/engine/IStaticPropMgr.h
	${SRC_DIR}/public/istudiorender.h
	${SRC_DIR}/public/vgui/ISurface.h
	${SRC_DIR}/public/vgui/ISystem.h
	${SRC_DIR}/public/materialsystem/itexture.h
	${SRC_DIR}/public/engine/ivdebugoverlay.h
	${SRC_DIR}/public/vgui/IVGui.h
	${SRC_DIR}/public/ivguicenterprint.h
	${SRC_DIR}/public/game/client/iviewport.h
	${SRC_DIR}/public/engine/ivmodelinfo.h
	${SRC_DIR}/public/engine/ivmodelrender.h
	${SRC_DIR}/public/ivrenderview.h
	${SRC_DIR}/public/jigglebones.h
	${SRC_DIR}/public/vgui/KeyCode.h
	${SRC_DIR}/public/tier1/KeyValues.h
	${SRC_DIR}/public/tier0/l2cache.h
	${SRC_DIR}/public/vgui_controls/Label.h
	${SRC_DIR}/public/vgui_controls/ListPanel.h
	${SRC_DIR}/public/mathlib/mathlib.h
	${SRC_DIR}/public/tier0/mem.h
	${SRC_DIR}/public/tier0/memalloc.h
	${SRC_DIR}/public/tier0/memdbgoff.h
	${SRC_DIR}/public/tier0/memdbgon.h
	${SRC_DIR}/public/tier1/mempool.h
	${SRC_DIR}/public/vgui_controls/Menu.h
	${SRC_DIR}/public/vgui_controls/MenuItem.h
	${SRC_DIR}/public/vgui_controls/MessageMap.h
	${SRC_DIR}/public/model_types.h
	${SRC_DIR}/public/vgui/MouseCode.h
	${SRC_DIR}/public/mouthinfo.h
	${SRC_DIR}/public/networkstringtabledefs.h
	${SRC_DIR}/public/networkvar.h
	${SRC_DIR}/public/vphysics/object_hash.h
	${SRC_DIR}/public/overlaytext.h
	${SRC_DIR}/public/vgui_controls/Panel.h
	${SRC_DIR}/public/vgui_controls/PanelAnimationVar.h
	${SRC_DIR}/public/vgui_controls/PanelListPanel.h
	${SRC_DIR}/public/vgui_controls/PHandle.h
	${SRC_DIR}/public/pixelwriter.h
	${SRC_DIR}/public/tier0/platform.h
	${SRC_DIR}/public/PlayerState.h
	${SRC_DIR}/public/tier1/processor_detect.h
	${SRC_DIR}/public/tier0/protected_things.h
	${SRC_DIR}/public/mathlib/polyhedron.h
	${SRC_DIR}/public/r_efx.h
	${SRC_DIR}/public/vstdlib/random.h
	${SRC_DIR}/public/tier1/rangecheckedvar.h
	${SRC_DIR}/public/renamed_recvtable_compat.h
	${SRC_DIR}/public/vgui_controls/RichText.h
	${SRC_DIR}/public/rope_physics.h
	${SRC_DIR}/public/rope_shared.h
	${SRC_DIR}/public/saverestoretypes.h
	${SRC_DIR}/public/scratchpad3d.h
	${SRC_DIR}/public/ScratchPadUtils.h
	${SRC_DIR}/public/vgui_controls/ScrollBar.h
	${SRC_DIR}/public/vgui_controls/SectionedListPanel.h
	${SRC_DIR}/public/sentence.h
	${SRC_DIR}/public/server_class.h
	${SRC_DIR}/public/shake.h
	${SRC_DIR}/public/shattersurfacetypes.h
	${SRC_DIR}/public/simple_physics.h
	${SRC_DIR}/public/tier1/smartptr.h
	${SRC_DIR}/public/soundchars.h
	${SRC_DIR}/public/soundflags.h
	${SRC_DIR}/public/soundinfo.h
	${SRC_DIR}/public/string_t.h
	${SRC_DIR}/public/tier1/stringpool.h
	${SRC_DIR}/public/stringregistry.h
	${SRC_DIR}/public/tier1/strtools.h
	${SRC_DIR}/public/studio.h
	${SRC_DIR}/public/surfinfo.h
	${SRC_DIR}/public/vgui_controls/TextEntry.h
	${SRC_DIR}/public/vgui_controls/TextImage.h
	${SRC_DIR}/public/texture_group_names.h
	${SRC_DIR}/public/vgui_controls/TreeView.h
	${SRC_DIR}/public/tier1/utlbidirectionalset.h
	${SRC_DIR}/public/tier1/utlbuffer.h
	${SRC_DIR}/public/tier1/utldict.h
	${SRC_DIR}/public/tier1/utlfixedmemory.h
	${SRC_DIR}/public/tier1/utlhash.h
	${SRC_DIR}/public/tier1/utllinkedlist.h
	${SRC_DIR}/public/tier1/utlmap.h
	${SRC_DIR}/public/tier1/utlmemory.h
	${SRC_DIR}/public/tier1/utlmultilist.h
	${SRC_DIR}/public/tier1/utlpriorityqueue.h
	${SRC_DIR}/public/tier1/utlqueue.h
	${SRC_DIR}/public/tier1/utlrbtree.h
	${SRC_DIR}/public/tier1/utlstack.h
	${SRC_DIR}/public/tier1/utlsymbol.h
	${SRC_DIR}/public/tier1/utlvector.h
	${SRC_DIR}/public/vallocator.h
	${SRC_DIR}/public/vcollide.h
	${SRC_DIR}/public/vcollide_parse.h
	${SRC_DIR}/public/mathlib/vector.h
	${SRC_DIR}/public/mathlib/vector2d.h
	${SRC_DIR}/public/mathlib/vector4d.h
	${SRC_DIR}/public/vgui/VGUI.h
	${SRC_DIR}/public/view_shared.h
	${SRC_DIR}/public/mathlib/vmatrix.h
	${SRC_DIR}/public/vphysics_interface.h
	${SRC_DIR}/public/mathlib/vplane.h
	${SRC_DIR}/public/tier0/vprof.h
	${SRC_DIR}/public/vstdlib/vstdlib.h
	${SRC_DIR}/public/vtf/vtf.h
	${SRC_DIR}/public/vgui_controls/WizardPanel.h
	${SRC_DIR}/public/vgui_controls/WizardSubPanel.h
	${SRC_DIR}/public/worldsize.h
	${SRC_DIR}/public/zip_uncompressed.h
)

source_group("Public Header Files" FILES ${PUBLIC_HEADER_FILES})

set(GAME_CONTROLS_SOURCES
	game_controls/baseviewport.cpp
	game_controls/basemodelpanel.cpp
	game_controls/basemodelpanel.h
	game_controls/basemodel_panel.cpp
	game_controls/basemodel_panel.h
	game_controls/ClientScoreBoardDialog.cpp
	game_controls/commandmenu.cpp
	game_controls/intromenu.cpp
	game_controls/MapOverview.cpp
	game_controls/NavProgress.cpp
	game_controls/SpectatorGUI.cpp
	game_controls/teammenu.cpp
	game_controls/vguitextwindow.cpp
	game_controls/IconPanel.cpp
)

source_group("Source Files/game_controls" FILES ${GAME_CONTROLS_SOURCES})

set(GAME_CONTROLS_HEADER_FILES
	game_controls/baseviewport.h
	game_controls/clientscoreboarddialog.h
	game_controls/commandmenu.h
	game_controls/imagemouseoverbutton.h
	game_controls/intromenu.h
	game_controls/mapoverview.h
	game_controls/mouseoverhtmlbutton.h
	game_controls/mouseoverpanelbutton.h
	game_controls/spectatorgui.h
	game_controls/teammenu.h
	game_controls/vguitextwindow.h
	game_controls/IconPanel.h
)

source_group("Header Files/game_controls Header Files" FILES ${GAME_CONTROLS_HEADER_FILES})

set(HAPTICS_SOURCES
	${SRC_DIR}/public/haptics/haptic_msgs.cpp
	$<${IS_WINDOWS}:${SRC_DIR}/public/haptics/haptic_utils.cpp>
	$<${IS_WINDOWS}:${SRC_DIR}/public/haptics/ihaptics.h>
	$<${IS_WINDOWS}:${SRC_DIR}/public/haptics/haptic_utils.h>
)

source_group("Haptics" FILES ${HAPTICS_SOURCES})

set_source_files_properties(
	youtubeapi.cpp
	${SRC_DIR}/common/movieobjects/timeutils.cpp
	${SRC_DIR}/public/bone_setup.cpp
	${SRC_DIR}/public/posedebugger.cpp
	${SRC_DIR}/public/client_class.cpp
	${SRC_DIR}/common/compiledcaptionswap.cpp
	${SRC_DIR}/public/collisionutils.cpp
	${SRC_DIR}/public/crtmemdebug.cpp
	${SRC_DIR}/public/dt_recv.cpp
	${SRC_DIR}/public/dt_utlvector_common.cpp
	${SRC_DIR}/public/dt_utlvector_recv.cpp
	${SRC_DIR}/public/filesystem_helpers.cpp
	${SRC_DIR}/public/interpolatortypes.cpp
	${SRC_DIR}/game/shared/interval.cpp
	${SRC_DIR}/common/language.cpp
	${SRC_DIR}/public/networkvar.cpp
	${SRC_DIR}/common/randoverride.cpp
	${SRC_DIR}/public/rope_physics.cpp
	${SRC_DIR}/public/scratchpad3d.cpp
	${SRC_DIR}/public/ScratchPadUtils.cpp
	${SRC_DIR}/public/sentence.cpp
	${SRC_DIR}/game/shared/sheetsimulator.cpp
	${SRC_DIR}/public/simple_physics.cpp
	${SRC_DIR}/public/stringregistry.cpp
	${SRC_DIR}/public/studio.cpp
	${SRC_DIR}/public/vallocator.cpp
	${SRC_DIR}/public/vgui_controls/vgui_controls.cpp
	${SRC_DIR}/public/jigglebones.cpp
	hud_lcd.cpp
	in_mouse.cpp
	mumble.cpp
	${SRC_DIR}/public/renamed_recvtable_compat.cpp
	rendertexture.cpp
	PROPERTIES SKIP_PRECOMPILE_HEADERS ON
)

function(target_use_client_base target EXCLUDE_SOURCES)
	set(USED_SOURCES
		${CLIENT_BASE_SOURCE_FILES}
		${CLIENT_BASE_HEADER_FILES}
		${CLIENT_MP3_SOURCE_FILES}
		${CLIENT_REPLAY_SOURCE_FILES}
		${CLIENT_SIXENSE_SOURCE_FILES}
		${TEMPENTS_SOURCES}
		${GAME_CONTROLS_SOURCES}
		${GAME_CONTROLS_HEADER_FILES}
		${GAME_SHARED_HEADER_FILES}
		${PUBLIC_HEADER_FILES}
	)

	if (${EXCLUDE_SOURCES})
		list(REMOVE_ITEM USED_SOURCES ${${EXCLUDE_SOURCES}})
	endif()

	target_sources(
		${target} PRIVATE
		${USED_SOURCES}
	)

	target_include_directories(
		${target} PRIVATE
		${SRC_DIR}/public
		${SRC_DIR}/public/appframework
		${SRC_DIR}/public/tier0
		${SRC_DIR}/public/tier1
		${SRC_DIR}/public/tier2
		${SRC_DIR}/public/tier3
		${SRC_DIR}/public/mathlib
		${SRC_DIR}/public/vstdlib
		${SRC_DIR}/public/vphysics
		${SRC_DIR}/public/vgui_controls
		${SRC_DIR}/game/client
		${SRC_DIR}/vgui2/include
		${SRC_DIR}/vgui2/controls
		${SRC_DIR}/game/shared
		${SRC_DIR}/game/client/game_controls
		${SRC_DIR}/thirdparty/sixensesdk/include
	)

	target_compile_definitions(
		${target} PRIVATE
		NO_STRING_T
		CLIENT_DLL
		VECTOR
		VERSION_SAFE_STEAM_API_INTERFACES
		PROTECTED_THINGS_ENABLE
		strncpy=use_Q_strncpy_instead
		_snprintf=use_Q_snprintf_instead
		$<${IS_WINDOWS}:fopen=dont_use_fopen>
		$<${IS_LINUX}:USE_WEBM_FOR_REPLAY>
		$<$<AND:${IS_WINDOWS},${BUILD_REPLAY}>:CURL_STATICLIB>
	)

	if (COMPILER_MSVC)
		target_compile_options(/wd4101)
		target_compile_options(/wd4005)
		target_compile_options(/wd4201)
		if (COMPILER_MSVC64)
			target_compile_options(/wd4267)
		endif()
	endif()

	target_precompile_headers(
		${target} PRIVATE
		cbase.h
	)

	target_link_libraries(
		${target} PRIVATE

		$<${IS_MACOS}:-framework Carbon>
		$<${IS_LINUX}:rt>
		$<${IS_WINDOWS}:winmm>
		$<$<AND:${IS_WINDOWS},${BUILD_REPLAY}>:wsock32;Ws2_32>
		particles

		bitmap
		choreoobjects
		dmxloader
		mathlib
		matsys_controls
		tier0
		tier1
		tier2
		tier3
		vgui_controls
		vtf
		steam_api

		#"$<${IS_POSIX}:libcrypto>"

		#"$<${IS_MACOS}:curl>"

		#"$<${IS_WINDOWS}:libcurl>"
		#"$<$<OR:${IS_WINDOWS},${IS_LINUX}>libz>"

		#"$<${IS_LINUX}:libcurl>"
		#"$<${IS_LINUX}:libcurlssl>"

		#"$<${IS_LINUX}:libssl>"

	)
endfunction()